apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-service
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail-service
  template:
    metadata:
      labels:
        app: mail-service
    spec:
      containers:
        - name: mail-service
          image: docker.io/orochiteam/itss2:k8s-mailservice
          envFrom:
            - secretRef:
                name: mail-credentials
            - secretRef:
                name: rabbitmq-credentials
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"
