version: "3"

services:
  server:
    container_name: server
    restart: always
    build:
      context: ../server/
      dockerfile: ../server/Dockerfile
      args:
        - DATABASE_URL=postgresql://itssuser:password@postgres:5432/itss2
    image: docker.io/orochiteam/itss2:${TAGS}
    depends_on:
      postgres:
        condition: service_started
    env_file:
      - ./backend/.backend.env
    networks:
      - itss2-backend
    ports:
      - ${PORT}:${PORT}
    healthcheck:
      test: wget --quiet --tries=1 --spider http://localhost:${PORT}/healthcheck || exit 1z
      interval: 30s
      timeout: 10s
      retries: 5

  postgres:
    container_name: postgres
    image: postgres:15
    env_file:
      - ./postgresql/.postgresql.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U itssuser"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - itss2-backend

  rabbitmq:
    image: rabbitmq:3.8.14-management-alpine
    container_name: rabbitmq
    env_file:
      - ./rabbitmq/.rabbitmq.env
    ports:
      - "${RABBITMQ_PORT_CONNECT}:${RABBITMQ_PORT_CONNECT}"
      - "${RABBITMQ_PORT_UI}:${RABBITMQ_PORT_UI}"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - itss2-backend

networks:
  itss2-backend:
    name: itss2-backend
    driver: bridge

volumes:
  postgres_data: {}
  rabbitmq-data: {}
